// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9mIiZNS1T1JRT6ndlWyK9FqWNqCqazZM',
    appId: '1:602389083426:web:259984bf68d887cbd3617b',
    messagingSenderId: '602389083426',
    projectId: 'flutter-chat-app-2e17b',
    authDomain: 'flutter-chat-app-2e17b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-2e17b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw5Sx04y39D-qwnMbRTqUF_3_9i_EvasA',
    appId: '1:602389083426:android:c8141a2f0413cff9d3617b',
    messagingSenderId: '602389083426',
    projectId: 'flutter-chat-app-2e17b',
    storageBucket: 'flutter-chat-app-2e17b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf8Jh4YSJrs5oxwnyaN_u0d0VNGI0B1m4',
    appId: '1:602389083426:ios:47c10bc03536bfb7d3617b',
    messagingSenderId: '602389083426',
    projectId: 'flutter-chat-app-2e17b',
    storageBucket: 'flutter-chat-app-2e17b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}